from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA_RAW = ROOT / "data" / "raw"
DATA_SEEDS = ROOT / "data" / "seeds"
DATA_PROCESSED = ROOT / "data" / "processed"
DATA_ANALYTICS = ROOT / "data" / "analytics"
OUTPUTS = ROOT / "outputs"
PROFILE_OUTPUTS = OUTPUTS / "tablas_resumen"
DOCS = ROOT / "docs"

PENDING_URL = "PENDIENTE_URL_DIRECTA"

SOURCE_CONFIG = {
    "F01": {
        "id_fuente": "F01",
        "nombre": "Oferta y Establecimientos Gastronomicos",
        "name": "Oferta y Establecimientos Gastronomicos",
        "organismo": "Ente de Turismo - GCBA",
        "description": "Registro de oferta y establecimientos gastronomicos publicado por Buenos Aires Data / GCBA.",
        "dataset_url": "https://data.buenosaires.gob.ar/dataset/oferta-establecimientos-gastronomicos",
        "download_url": "https://data.buenosaires.gob.ar/dataset/oferta-establecimientos-gastronomicos/resource/e66613ef-aaf4-44aa-b89c-638c431fef0e/download",
        "download_url_cdn": "https://cdn.buenosaires.gob.ar/datosabiertos/datasets/ente-de-turismo/oferta-establecimientos-gastronomicos/establecimientos_gastronomicos.csv",
        "url": "https://data.buenosaires.gob.ar/dataset/oferta-establecimientos-gastronomicos/resource/e66613ef-aaf4-44aa-b89c-638c431fef0e/download",
        "output_filename": "f01_oferta_establecimientos_gastronomicos.csv",
        "target_filename": "f01_oferta_establecimientos_gastronomicos.csv",
        "formato": "csv",
        "prioridad": "alta",
        "fecha_consulta": "2026-06-10",
        "limitaciones": "Puede tener mojibake; trae lat/lon de fuente para mapa; no trae fecha por registro; puede estar desactualizado.",
        "required_strict": True,
        "seed_glob": "raw_establecimientos_gastronomicos.csv",
        "raw_patterns": [
            "f01_*.csv",
            "*oferta*establecimientos*gastronom*.csv",
            "*establecimientos*gastronom*.csv",
        ],
        "portal_url": "https://data.buenosaires.gob.ar/dataset/oferta-establecimientos-gastronomicos",
    },
}

_F02_RESOURCES = {
    "F02_2015_2018": ("2015_2018", "2015-2018", "https://data.buenosaires.gob.ar/dataset/habilitaciones-aprobadas/resource/748176e8-298f-4bda-aa44-3ef4dc560c8c/download"),
    "F02_2019": ("2019", "2019", "https://data.buenosaires.gob.ar/dataset/habilitaciones-aprobadas/resource/21343579-cf7e-4fb8-a3bc-8d41710cb077/download"),
    "F02_2020": ("2020", "2020", "https://data.buenosaires.gob.ar/dataset/habilitaciones-aprobadas/resource/dd6760a4-92e5-4c43-83f5-33181bac37d8/download"),
    "F02_2021": ("2021", "2021", "https://data.buenosaires.gob.ar/dataset/habilitaciones-aprobadas/resource/120a24f6-35f5-49b7-9db2-a03cf621cc36/download"),
    "F02_2022": ("2022", "2022", "https://data.buenosaires.gob.ar/dataset/habilitaciones-aprobadas/resource/ed26ea8a-b2dd-4543-a2bb-cd613c99b393/download"),
    "F02_2023": ("2023", "2023", "https://data.buenosaires.gob.ar/dataset/habilitaciones-aprobadas/resource/72be4960-7a64-4c31-9751-15155cadf327/download"),
    "F02_2024": ("2024", "2024", "https://data.buenosaires.gob.ar/dataset/habilitaciones-aprobadas/resource/af7cb21d-3c26-4227-8271-a898442bf99b/download"),
    "F02_2025": ("2025", "2025", "https://data.buenosaires.gob.ar/dataset/habilitaciones-aprobadas/resource/00cab09a-06fa-43d0-b000-e6b2364a3082/download"),
}

for key, (suffix, periodo, url) in _F02_RESOURCES.items():
    SOURCE_CONFIG[key] = {
        "id_fuente": "F02",
        "nombre": f"Habilitaciones Aprobadas AGC {periodo}",
        "name": f"Habilitaciones Aprobadas AGC {periodo}",
        "organismo": "Agencia Gubernamental de Control - GCBA",
        "description": "Habilitaciones aprobadas publicadas por Buenos Aires Data / AGC.",
        "dataset_url": "https://data.buenosaires.gob.ar/dataset/habilitaciones-aprobadas",
        "download_url": url,
        "url": url,
        "output_filename": f"f02_habilitaciones_aprobadas_{suffix}.csv",
        "target_filename": f"f02_habilitaciones_aprobadas_{suffix}.csv",
        "formato": "csv",
        "prioridad": "alta",
        "fecha_consulta": "2026-06-10",
        "limitaciones": "Clasificacion gastronomica inferida desde descripcion de rubro; no se exige recurso 2026.",
        "periodo_fuente": periodo,
        "anio_fuente": periodo,
        "required_strict": True,
        "seed_glob": "raw_habilitaciones_aprobadas*.csv",
        "raw_patterns": [f"f02_habilitaciones_aprobadas_{suffix}.csv"],
        "portal_url": "https://data.buenosaires.gob.ar/dataset/habilitaciones-aprobadas",
    }

SOURCE_CONFIG["F02_2026"] = {
    "id_fuente": "F02",
    "nombre": "Habilitaciones Aprobadas AGC 2026",
    "name": "Habilitaciones Aprobadas AGC 2026",
    "organismo": "Agencia Gubernamental de Control - GCBA",
    "description": "Entrada opcional futura; no publicada al momento de consulta.",
    "dataset_url": "https://data.buenosaires.gob.ar/dataset/habilitaciones-aprobadas",
    "download_url": None,
    "url": None,
    "output_filename": "f02_habilitaciones_aprobadas_2026.csv",
    "target_filename": "f02_habilitaciones_aprobadas_2026.csv",
    "formato": "csv",
    "prioridad": "baja",
    "fecha_consulta": "2026-06-10",
    "limitaciones": "No publicado; no requerido para strict-real.",
    "periodo_fuente": "2026",
    "anio_fuente": "2026",
    "required_strict": False,
    "seed_glob": "raw_habilitaciones_aprobadas*.csv",
    "raw_patterns": ["f02_habilitaciones_aprobadas_2026.csv"],
    "portal_url": "https://data.buenosaires.gob.ar/dataset/habilitaciones-aprobadas",
}

SOURCE_CONFIG.update(
    {
        "F03": {
            "id_fuente": "F03",
            "nombre": "Ferias y Mercados",
            "name": "Ferias y Mercados",
            "organismo": "DG Ferias - Ministerio de Ambiente y Espacio Publico - GCBA",
            "description": "CSV combinado de ferias y mercados publicado por Buenos Aires Data / GCBA.",
            "dataset_url": "https://data.buenosaires.gob.ar/dataset/ferias-mercados",
            "download_url": "https://data.buenosaires.gob.ar/dataset/ferias-mercados/resource/juqdkmgo-1125-resource/download",
            "url": "https://data.buenosaires.gob.ar/dataset/ferias-mercados/resource/juqdkmgo-1125-resource/download",
            "output_filename": "f03_ferias_mercados.csv",
            "target_filename": "f03_ferias_mercados.csv",
            "formato": "csv",
            "prioridad": "alta",
            "fecha_consulta": "2026-06-10",
            "limitaciones": "Geometria completa no disponible; GeoJSON separado representa solo FIAB.",
            "required_strict": True,
            "seed_glob": "raw_ferias_mercados.csv",
            "raw_patterns": ["f03_ferias_mercados.csv"],
            "portal_url": "https://data.buenosaires.gob.ar/dataset/ferias-mercados",
        },
        "F03_FERIAS": {
            "id_fuente": "F03",
            "nombre": "Ferias",
            "name": "Ferias",
            "organismo": "DG Ferias - Ministerio de Ambiente y Espacio Publico - GCBA",
            "description": "CSV complementario solo ferias.",
            "dataset_url": "https://data.buenosaires.gob.ar/dataset/ferias-mercados",
            "download_url": "https://data.buenosaires.gob.ar/dataset/ferias-mercados/resource/juqdkmgo-1121-resource/download",
            "url": "https://data.buenosaires.gob.ar/dataset/ferias-mercados/resource/juqdkmgo-1121-resource/download",
            "output_filename": "f03_ferias.csv",
            "target_filename": "f03_ferias.csv",
            "formato": "csv",
            "prioridad": "media",
            "fecha_consulta": "2026-06-10",
            "limitaciones": "Recurso complementario; F03 combinado es el requerido para strict-real.",
            "required_strict": False,
            "seed_glob": "raw_ferias_mercados.csv",
            "raw_patterns": ["f03_ferias.csv"],
            "portal_url": "https://data.buenosaires.gob.ar/dataset/ferias-mercados",
        },
        "F03_MERCADOS": {
            "id_fuente": "F03",
            "nombre": "Mercados",
            "name": "Mercados",
            "organismo": "DG Ferias - Ministerio de Ambiente y Espacio Publico - GCBA",
            "description": "CSV complementario solo mercados.",
            "dataset_url": "https://data.buenosaires.gob.ar/dataset/ferias-mercados",
            "download_url": "https://data.buenosaires.gob.ar/dataset/ferias-mercados/resource/juqdkmgo-1126-resource/download",
            "url": "https://data.buenosaires.gob.ar/dataset/ferias-mercados/resource/juqdkmgo-1126-resource/download",
            "output_filename": "f03_mercados.csv",
            "target_filename": "f03_mercados.csv",
            "formato": "csv",
            "prioridad": "media",
            "fecha_consulta": "2026-06-10",
            "limitaciones": "Recurso complementario; F03 combinado es el requerido para strict-real.",
            "required_strict": False,
            "seed_glob": "raw_ferias_mercados.csv",
            "raw_patterns": ["f03_mercados.csv"],
            "portal_url": "https://data.buenosaires.gob.ar/dataset/ferias-mercados",
        },
        "F03_FIAB_GEOJSON": {
            "id_fuente": "F03",
            "nombre": "FIAB GeoJSON",
            "name": "FIAB GeoJSON",
            "organismo": "DG Ferias - Ministerio de Ambiente y Espacio Publico - GCBA",
            "description": "GeoJSON solo FIAB; no representa todas las ferias y mercados.",
            "dataset_url": "https://data.buenosaires.gob.ar/dataset/ferias-mercados",
            "download_url": "https://data.buenosaires.gob.ar/dataset/ferias-mercados/resource/89d4e504-2fa8-4703-9c05-2471fa47cdfa/download",
            "url": "https://data.buenosaires.gob.ar/dataset/ferias-mercados/resource/89d4e504-2fa8-4703-9c05-2471fa47cdfa/download",
            "output_filename": "f03_fiab.geojson",
            "target_filename": "f03_fiab.geojson",
            "formato": "geojson",
            "prioridad": "baja",
            "fecha_consulta": "2026-06-10",
            "limitaciones": "Solo FIAB; no tratar como capa geografica completa de F03.",
            "required_strict": False,
            "seed_glob": "",
            "raw_patterns": ["f03_fiab.geojson"],
            "portal_url": "https://data.buenosaires.gob.ar/dataset/ferias-mercados",
        },
        "F04": {
            "id_fuente": "F04",
            "nombre": "Eventos gastronomicos semiestructurados",
            "name": "Eventos gastronomicos semiestructurados",
            "organismo": "Relevamiento propio sobre GCBA, Turismo BA, Boletin Oficial y fuentes complementarias",
            "description": "Relevamiento manual trazable de eventos, ciclos, concursos y activaciones vinculados a politica gastronomica de CABA.",
            "dataset_url": "relevamiento_manual_trazable",
            "download_url": None,
            "url": None,
            "output_filename": "f04_eventos_gastronomicos.csv",
            "target_filename": "f04_eventos_gastronomicos.csv",
            "formato": "csv",
            "prioridad": "media",
            "fecha_consulta": "2026-06-10",
            "limitaciones": "No es dataset oficial estructurado; no representa el universo completo de eventos gastronomicos.",
            "required_strict": True,
            "seed_glob": "raw_eventos_gastronomicos.csv",
            "raw_patterns": ["f04_eventos_gastronomicos.csv"],
            "portal_url": "relevamiento_manual_trazable",
        },
        "F05": {
            "id_fuente": "F05",
            "nombre": "Programas y politicas gastronomicas semiestructuradas",
            "name": "Programas y politicas gastronomicas semiestructuradas",
            "organismo": "Relevamiento propio sobre GCBA, normativa, Boletin Oficial y fuentes complementarias",
            "description": "Catalogo manual trazable de programas, politicas, normativa e instrumentos vinculados a gastronomia en CABA.",
            "dataset_url": "relevamiento_manual_trazable",
            "download_url": None,
            "url": None,
            "output_filename": "f05_programas_politicas_gastronomicas.csv",
            "target_filename": "f05_programas_politicas_gastronomicas.csv",
            "formato": "csv",
            "prioridad": "media",
            "fecha_consulta": "2026-06-10",
            "limitaciones": "No es dataset oficial estructurado; catalogo curado, no serie temporal de impacto.",
            "required_strict": True,
            "seed_glob": "raw_programas_politicas.csv",
            "raw_patterns": ["f05_programas_politicas_gastronomicas.csv"],
            "portal_url": "relevamiento_manual_trazable",
        },
    }
)

# Backwards-compatible alias used by earlier scripts.
SOURCES = {key: item.get("download_url") for key, item in SOURCE_CONFIG.items()}

BARRIO_COMUNA = {
    "Agronomia": "15",
    "Almagro": "5",
    "Balvanera": "3",
    "Barracas": "4",
    "Belgrano": "13",
    "Boedo": "5",
    "Caballito": "6",
    "Chacarita": "15",
    "Coghlan": "12",
    "Colegiales": "13",
    "Constitucion": "1",
    "Flores": "7",
    "Floresta": "10",
    "La Boca": "4",
    "La Paternal": "15",
    "Liniers": "9",
    "Mataderos": "9",
    "Monte Castro": "10",
    "Monserrat": "1",
    "Nueva Pompeya": "4",
    "Nunez": "13",
    "Palermo": "14",
    "Parque Avellaneda": "9",
    "Parque Chacabuco": "7",
    "Parque Chas": "15",
    "Parque Patricios": "4",
    "Puerto Madero": "1",
    "Recoleta": "2",
    "Retiro": "1",
    "Saavedra": "12",
    "San Cristobal": "3",
    "San Nicolas": "1",
    "San Telmo": "1",
    "Velez Sarsfield": "10",
    "Versalles": "10",
    "Villa Crespo": "15",
    "Villa del Parque": "11",
    "Villa Devoto": "11",
    "Villa General Mitre": "11",
    "Villa Lugano": "8",
    "Villa Luro": "10",
    "Villa Ortuzar": "15",
    "Villa Pueyrredon": "12",
    "Villa Real": "10",
    "Villa Riachuelo": "8",
    "Villa Santa Rita": "11",
    "Villa Soldati": "8",
    "Villa Urquiza": "12",
}

SOURCE_STATUS_VALUES = {
    "seed": "datos seed",
    "partial": "datos reales parciales",
    "complete": "datos reales completos",
    "pending": "datos pendientes de validacion",
}
